# -*- coding: utf-8 -*-
"""gateassignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iK2Xn7FTN1y4T_dL2KSOdxv-n69wWhpI
"""

import numpy as np
from scipy import signal
import matplotlib.pyplot as plt

#a=0,b=1
'''
def h(n):
  t=0
  if(n==0):
      t=1
  elif(n==1):
      t=0
  elif(n==2):
      t=1
  else:
      t=0
  return t
'''
h=np.array([1,0,1])

def H(z):
    num = h[0]*(z**2) + h[1]*(z) + h[2]
    denom = z**2 
    return num/denom

w_range = np.linspace( -1*np.pi, 1*np.pi, 1000)
plt.plot(w_range, np.abs(H(np.exp(1j*w_range))))
plt.ylabel('|H(e^(jw))|')
plt.xlabel('w')