# -*- coding: utf-8 -*-
"""quiz2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jjnzUEZp3ZnX2Gpg2MfuboToKWwbhdp_
"""

import numpy
from scipy import signal
import random
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.lines as mlines

N = random.randint(2,100)
b=[0]*(N-1)
b.append(-1)
b.insert(0,1)

a=[1,-1]

zeros =signal.tf2zpk(b, a)[0]
poles =signal.tf2zpk(b, a)[1]

fig, ax = plt.subplots(figsize = (6,6))

ax.set_xlim([-1.5,1.5])
ax.set_ylim([-1.5,1.5])

print("For N =",N)
print("poles=",poles)
print("zeros=",zeros)
zero, = plt.plot(zeros.real,zeros.imag, 'ro',label = 'Zeros')
pole, = plt.plot(poles.real,[0], 'rx',label = 'Poles',color='black')

legend = plt.legend(handles =[pole,zero], loc = 'lower right')
fig.gca().add_artist(legend)

circle = plt.Circle([0,0],0.03,color = 'w')
fig.gca().add_artist(circle)

circle = plt.Circle([0,0],1,edgecolor = 'black',fill = 0,linestyle = '--')
fig.gca().add_artist(circle)

circle = plt.Circle([0,0],0.03,edgecolor = 'green',fill = 0,linestyle = '--')
fig.gca().add_artist(circle)


patches = mpatches.Patch(color="yellow", label="ROC")
dotted_line = mlines.Line2D([],[],color = 'black',label='Unit circle')
dotted_line.set_linestyle('--')
plt.legend(handles=[patches,dotted_line], loc = 'upper right')
ax.set_facecolor('xkcd:yellow')

plt.grid()
plt.xlabel("Re")
plt.ylabel("Im")
plt.show()