# -*- coding: utf-8 -*-
"""amplitude.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tjRkvYBF7xBES58mgETJIezE_FYa_J-d
"""

import matplotlib.pyplot as plt
import numpy as np
from math import *

n= np.arange(0,38, 0.1);
x  = np.sin((pi*n)/(19))

plt.plot(n,np.abs(x))
plt.grid()
plt.xlabel("n")
plt.ylabel("|x[n]|")

plt.show()